### ISSUE TITLE
ImportError: No module named abc

### ISSUE THREAD

**Issue by lishen565** [labfor/DeepBurning#1]
hi all, after I typed "bash run_SMAC.sh" in console, something went wrong as below:
[INFO ] Logging to: /home/lishen/公共的/YOSO/smac-output/train-scenario/log-run816788458.txt
[INFO ] Version of SMAC is v2.10.03-master-778 (3ee628ef9bf2), running on OpenJDK 64-Bit Server VM (1.8.0_171) and Linux 4.13.0-46-generic (amd64) 
[INFO ] Call String: smac --scenario-file train-scenario.txt 
[INFO ] SMAC started at: 2020-2-10 22:52:26. Minimizing mean quality.
[WARN ] [PROCESS-ERR]  Traceback (most recent call last):
[WARN ] [PROCESS-ERR]    File "smc_train.py", line 3, in <module>
[WARN ] [PROCESS-ERR]      import train
[WARN ] [PROCESS-ERR]    File "/home/lishen/公共的/YOSO/train.py", line 16, in <module>
[WARN ] [PROCESS-ERR]      from mlp_evaluation import  MLP_network,TestMLP_network,print_res
[WARN ] [PROCESS-ERR]    File "/home/lishen/公共的/YOSO/mlp_evaluation.py", line 1, in <module>
[WARN ] [PROCESS-ERR]      from nn_dataflow.core import Network
[WARN ] [PROCESS-ERR]    File "/usr/local/lib/python2.7/dist-packages/nn_dataflow/core/__init__.py", line 38, in <module>
[WARN ] [PROCESS-ERR]      from .nn_dataflow_scheme import NNDataflowScheme
[WARN ] [PROCESS-ERR]    File "/usr/local/lib/python2.7/dist-packages/nn_dataflow/core/nn_dataflow_scheme.py", line 18, in <module>
[WARN ] [PROCESS-ERR]      from collections.abc import MutableMapping
**[WARN ] [PROCESS-ERR]  ImportError: No module named abc**
[ERROR] The following algorithm call failed: cd "/home/lishen/公共的/YOSO" ;  python2 smc_train.py -Alpha 0.9 -Beta 0.09 -Gamma 0.01 no_instance 0 1.7976931348623157E308 2147483647 -1 -HIDDEN_NODE_FC1 '16' -HIDDEN_NODE_FC2 '12' -HIDDEN_NODE_FC3 '12'  
Error occurred while running SMAC
>Error Message: Wrapper did not output anything that matched the expected output ("Result of algorithm run:..."). Please try executing the wrapper directly
>Encountered Exception:TargetAlgorithmAbortException
>Error Log Location: /home/lishen/公共的/YOSO/smac-output/train-scenario/log-run816788458.txt
[ERROR] Message:  Wrapper did not output anything that matched the expected output ("Result of algorithm run:..."). Please try executing the wrapper directly
[ERROR] We tried to call the target algorithm wrapper, but this call failed.
[ERROR] The problem is (most likely) somewhere in the wrapper or with the arguments to SMAC.
[ERROR] The easiest way to debug this problem is to manually execute the call we tried and see why it did not return the correct result
[ERROR] The required output of the wrapper is something like "Result for ParamILS: x,x,x,x,x".);
[INFO ] Exiting SMAC with failure. Log: /home/lishen/公共的/YOSO/smac-output/train-scenario/log-run816788458.txt
[INFO ] For a list of available commands use:  --help
[INFO ] The Quickstart guide at available at: http://www.cs.ubc.ca/labs/beta/Projects/SMAC/ or alternatively (doc/quickstart.html) gives simple examples for getting up and running.
[INFO ] The FAQ (doc/faq.pdf) contains commonly asked questions regarding troubleshooting, and usage.
[INFO ] The Manual (doc/manual.pdf) contains detailed information on file format semantics.
[INFO ] If you are stuck, please ask a question in the SMAC forum: https://groups.google.com/forum/#!forum/smac-forum

Have you ever met this problem and is there any way to install collections.abc? 
PS. I've tried to pip install collections, but it said as below:
The directory '/home/lishen/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/lishen/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting collections
  Could not find a version that satisfies the requirement collections (from versions: )
No matching distribution found for collections

Thanks a lot if anybody can help.

**Comment by lishen565** [comment]
Hi，I‘ve solved this issue by pip install nn-dataflow==1.5.(I didn't install the specified version as your guidance )
